import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-neutral-950"}>
        {children}
        <Image
          className="w-full absolute inset-0"
          unoptimized
          alt=""
          height={500}
          width={500}
          src={"blk_noise.png"}
        />
      </body>
    </html>
  );
}
